static const char black[]       = "#24273a";
static const char gray2[]       = "#6b6f84"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#b7bdf8"; // focused window border
static const char green[]       = "#a6e3a1";
static const char red[]         = "#e06c75";
static const char orange[]      = "#fab387";
static const char yellow[]      = "#E5C07B";
static const char pink[]        = "#E98CA4";
static const char purple[]      = "#89dceb";
static const char cyan[]        = "#56B6C2";
static const char col_borderbar[]  = "#24273a"; // inner border
